language: go
go:
  - 1.11.x
  - master
install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/CharLemAznable/wechataes
  - go get github.com/CharLemAznable/gokits
  - go get github.com/CharLemAznable/varys
script: go build
