Port = 4236
ContextPath = ""
LogLevel = "info"
ClusterNodeAddresses = [ "http://localhost:4236" ]

DriverName = "mysql"
DataSourceName = "admin:test123@tcp(127.0.0.1:3306)/varys?charset=utf8"

WechatAppTokenURL = "https://api.weixin.qq.com/cgi-bin/token"
WechatAppConfigLifeSpan = "60m"
WechatAppTokenLifeSpan = "5m"
WechatAppTokenTempLifeSpan = "1m"
WechatAppProxyURL = "https://api.weixin.qq.com/"
WechatAppMpLoginProxyURL = "https://api.weixin.qq.com/sns/"

WechatTpTokenURL = "https://api.weixin.qq.com/cgi-bin/component/api_component_token"
WechatTpConfigLifeSpan = "60m"
WechatTpCryptorLifeSpan = "60m"
WechatTpTokenLifeSpan = "5m"
WechatTpTokenTempLifeSpan = "1m"
WechatTpProxyURL = "https://api.weixin.qq.com/"

WechatTpPreAuthCodeURL = "https://api.weixin.qq.com/cgi-bin/component/api_create_preauthcode?component_access_token="
WechatTpQueryAuthURL = "https://api.weixin.qq.com/cgi-bin/component/api_query_auth?component_access_token="
WechatTpRefreshAuthURL = "https://api.weixin.qq.com/cgi-bin/component/api_authorizer_token?component_access_token="
WechatTpAuthTokenLifeSpan = "5m"
WechatTpAuthTokenTempLifeSpan = "1m"
WechatTpAuthProxyURL = "https://api.weixin.qq.com/"
WechatTpAuthMpLoginProxyURL = "https://api.weixin.qq.com/sns/component/"

WechatCorpTokenURL = "https://qyapi.weixin.qq.com/cgi-bin/gettoken"
WechatCorpConfigLifeSpan = "60m"
WechatCorpTokenMaxLifeSpan = "5m"
WechatCorpTokenExpireCriticalSpan = "1s"
WechatCorpProxyURL = "https://qyapi.weixin.qq.com/"

WechatCorpTpTokenURL = "https://qyapi.weixin.qq.com/cgi-bin/service/get_suite_token"
WechatCorpTpConfigLifeSpan = "60m"
WechatCorpTpCryptorLifeSpan = "60m"
WechatCorpTpTokenMaxLifeSpan = "5m"
WechatCorpTpTokenExpireCriticalSpan = "1s"

WechatCorpTpPreAuthCodeURL = "https://qyapi.weixin.qq.com/cgi-bin/service/get_pre_auth_code?suite_access_token="
WechatCorpTpPermanentCodeURL = "https://qyapi.weixin.qq.com/cgi-bin/service/get_permanent_code?suite_access_token="
WechatCorpTpAuthTokenURL = "https://qyapi.weixin.qq.com/cgi-bin/service/get_corp_token?suite_access_token="
WechatCorpTpPermanentCodeLifeSpan = "60m"
WechatCorpTpAuthTokenMaxLifeSpan = "5m"
WechatCorpTpAuthTokenExpireCriticalSpan = "1s"

WechatJsapiTicketURL = "https://api.weixin.qq.com/cgi-bin/ticket/getticket"

ToutiaoAppTokenURL = "https://developer.toutiao.com/api/apps/token"
ToutiaoAppConfigLifeSpan = "60m"
ToutiaoAppTokenLifeSpan = "5m"
ToutiaoAppTokenTempLifeSpan = "1m"

FengniaoAppTokenURL = "https://open-anubis.ele.me/anubis-webapi/openapi/token"
FengniaoAppRefreshURL = "https://open-anubis.ele.me/anubis-webapi/openapi/refreshToken"
FengniaoAppConfigLifeSpan = "60m"
FengniaoAppTokenLifeSpan = "8m"
FengniaoAppProxyURL = "https://open-anubis.ele.me/anubis-webapi/v3/invoke/"
