package main

const queryWechatCorpConfigSQL = `
SELECT C.CORP_ID ,C.CORP_SECRET
  FROM WECHAT_CORP_CONFIG C
 WHERE C.ENABLED   = 1
   AND C.CODE_NAME = ?
`

const queryWechatCorpTokenSQL = `
SELECT T.CORP_ID ,T.ACCESS_TOKEN
      ,UNIX_TIMESTAMP(T.EXPIRE_TIME) AS EXPIRE_TIME
  FROM WECHAT_CORP_TOKEN T
 WHERE T.CODE_NAME = ?
`

const createWechatCorpTokenSQL = `
INSERT INTO WECHAT_CORP_TOKEN
      (CODE_NAME    ,CORP_ID
      ,ACCESS_TOKEN ,EXPIRE_TIME)
SELECT C.CODE_NAME  ,C.CORP_ID
      ,?            ,FROM_UNIXTIME(?)
  FROM WECHAT_CORP_CONFIG C
 WHERE C.ENABLED   = 1
   AND C.CODE_NAME = ?
`

const updateWechatCorpTokenSQL = `
UPDATE WECHAT_CORP_TOKEN
   SET ACCESS_TOKEN = ?
      ,EXPIRE_TIME  = FROM_UNIXTIME(?)
 WHERE CODE_NAME    = ?
   AND EXPIRE_TIME  < NOW()
`
