package main

const queryWechatTpConfigSQL = `
SELECT C.APP_ID ,C.APP_SECRET ,C.TOKEN ,C.AES_KEY ,C.REDIRECT_URL
  FROM WECHAT_APP_THIRD_PLATFORM_CONFIG C
 WHERE C.ENABLED    = 1
   AND C.CODE_NAME  = ?
`

const updateWechatTpTicketSQL = `
REPLACE INTO WECHAT_APP_THIRD_PLATFORM_TICKET
      (CODE_NAME    ,APP_ID     ,TICKET)
SELECT C.CODE_NAME  ,C.APP_ID   ,?
  FROM WECHAT_APP_THIRD_PLATFORM_CONFIG C
 WHERE C.ENABLED    = 1
   AND C.CODE_NAME  = ?
`

const queryWechatTpTicketSQL = `
SELECT T.TICKET
  FROM WECHAT_APP_THIRD_PLATFORM_TICKET T
 WHERE T.CODE_NAME  = ?
`

const queryWechatTpTokenSQL = `
SELECT T.APP_ID ,T.ACCESS_TOKEN ,T.UPDATED 
      ,UNIX_TIMESTAMP(T.EXPIRE_TIME) AS EXPIRE_TIME
  FROM WECHAT_APP_THIRD_PLATFORM_TOKEN T
 WHERE T.CODE_NAME  = ?
`

const createWechatTpTokenSQL = `
INSERT INTO WECHAT_APP_THIRD_PLATFORM_TOKEN
      (CODE_NAME    ,APP_ID     ,UPDATED)
SELECT C.CODE_NAME  ,C.APP_ID   ,0
  FROM WECHAT_APP_THIRD_PLATFORM_CONFIG C
 WHERE C.ENABLED    = 1
   AND C.CODE_NAME  = ?
`

const updateWechatTpTokenSQL = `
UPDATE WECHAT_APP_THIRD_PLATFORM_TOKEN
   SET UPDATED      = 0
 WHERE CODE_NAME    = ?
   AND UPDATED      = 1
   AND EXPIRE_TIME  < NOW()
`

const uncompleteWechatTpTokenSQL = `
UPDATE WECHAT_APP_THIRD_PLATFORM_TOKEN
   SET UPDATED      = 1
 WHERE CODE_NAME    = ?
   AND UPDATED      = 0
`

const completeWechatTpTokenSQL = `
UPDATE WECHAT_APP_THIRD_PLATFORM_TOKEN
   SET UPDATED      = 1
      ,ACCESS_TOKEN = ?
      ,EXPIRE_TIME  = DATE_ADD(NOW(), INTERVAL ? SECOND)
 WHERE CODE_NAME    = ?
   AND UPDATED      = 0
`
